Repository Ashfaq-Ahmed-Mohammed/Team-CourtLink, pull requests merged in 2025-04, with the labels that each got.

#182 Added the sprint 3 folder and sub folders
  Sprint3/Pics/CourtNavbarComponent_TestCases.jpeg
  Sprint3/Pics/Court_TestCases.jpeg
  Sprint3/Pics/CreateBooking_TestCase.jpeg
  Sprint3/Pics/CreateCustomer_TestCase.jpeg
  Sprint3/Pics/CypressTest_Result.jpeg
  Sprint3/Pics/CypressTest_Setup.jpeg
  Sprint3/Pics/SportComponent_TestCase.png
  Sprint3/Sprint3.md
Labels: documentation, sprint 3

#184 Cancellation code done
  CourtLink.db
  CourtLink/src/app/components/my-bookings/my-bookings.component.html
  CourtLink/src/app/components/my-bookings/my-bookings.component.ts
Labels: enhancement, sprint 4

#188 Added a hmaburger icon with logout and contact us option
  CourtLink/src/app/app.config.ts
  CourtLink/src/app/components/navbar/navbar.component.html
  CourtLink/src/app/components/navbar/navbar.component.ts
Labels: bug, sprint 4

#190 Added a slideshow and a login button
  .DS_Store
  CourtLink.db
  CourtLink/package-lock.json
  CourtLink/package.json
  CourtLink/src/app/app.routes.ts
  CourtLink/src/app/components/navbar/navbar.component.ts
  CourtLink/src/app/components/sports/sports.component.html
  CourtLink/src/app/components/sports/sports.component.ts
  CourtLink/src/assets/images/slide1.jpg
  CourtLink/src/assets/images/slide2.jpg
  CourtLink/src/assets/images/slide3.png
  CourtLink/src/assets/images/slide4.jpeg
  CourtLink/src/assets/images/slide5.jpg
  CourtLink/src/assets/images/slide6.webp
  CourtLink/src/assets/images/slide7.jpg
  CourtLink/src/assets/images/slide8.jpg
  CourtLink/src/assets/images1/slide1.jpg
  CourtLink/src/assets/images1/slide2.jpg
  CourtLink/src/assets/images1/slide3.png
  CourtLink/src/assets/images1/slide4.jpeg
  CourtLink/src/assets/images1/slide5.jpg
  CourtLink/src/assets/images1/slide6.webp
  CourtLink/src/assets/images1/slide7.jpg
  CourtLink/src/assets/images1/slide8.jpg
  CourtLink/src/main.ts
  CourtLink/tailwind.config.js
Labels: enhancement, sprint 4

#199 Added the backend support for the Admin login and updated sql.txt file
  BackEnd/Admin/AdminLogin.go
  BackEnd/DataBase/DataBase.go
  BackEnd/go.mod
  BackEnd/go.sum
  BackEnd/main.go
  CourtLink.db
  sql.txt
Labels: enhancement, sprint 4

#200 Added more testcases for the listcourts and listbookings APIs
  BackEnd/Court/ListCourts_test.go
Labels: testing, sprint 4

#201 Unit testing on navbar and sports components for new functionality and end to end cypress testing done
  CourtLink/cypress/cypress.config.ts
  CourtLink/cypress/e2e/home.cy.ts
  CourtLink/cypress/support/commands.ts
  CourtLink/src/app/components/navbar/navbar.component.spec.ts
  CourtLink/src/app/components/sports/sports.component.spec.ts
  CourtLink/src/app/components/sports/sports.component.ts
Labels: testing, sprint 4

#203 Added swagger doc for Admin Login API
  BackEnd/Admin/AdminLogin.go
  BackEnd/docs/docs.go
  BackEnd/docs/swagger.json
  BackEnd/docs/swagger.yaml
Labels: documentation, sprint 4

#208 Added functionality to reset slots on court name
  BackEnd/Court/UpdateCourts.go
  BackEnd/Utils/ResetSlots.go
  BackEnd/main.go
Labels: enhancement, sprint 4

#211 added login for admin
  CourtLink/src/app/app.routes.ts
  CourtLink/src/app/components/admin-login/admin-login.component.css
  CourtLink/src/app/components/admin-login/admin-login.component.html
  CourtLink/src/app/components/admin-login/admin-login.component.spec.ts
  CourtLink/src/app/components/admin-login/admin-login.component.ts
Labels: enhancement, sprint 4

#213 Added Swagger documentation for the reset API
  BackEnd/Utils/ResetSlots.go
  BackEnd/docs/docs.go
  BackEnd/docs/swagger.json
  BackEnd/docs/swagger.yaml
Labels: documentation, sprint 4

#215 Added the test cases for new AdminLogin API and added more test cases for list sports and create customer
  BackEnd/Admin/AdminLogin_test.go
  BackEnd/Court/UpdateCourts_test.go
  BackEnd/Customer/CreateCustomer_test.go
  BackEnd/Sport/ListSports_test.go
Labels: testing, sprint 4

#223 unit tested the admin-login component
  CourtLink/src/app/components/admin-login/admin-login.component.spec.ts
Labels: testing, sprint 4
