Repository Ashfaq-Ahmed-Mohammed/Team-CourtLink, pull requests merged in 2025-03, with the labels that each got.

#63 Booking post capability is added
  BackEnd/Bookings/CreateBooking.go
  BackEnd/DataBase/DataBase.go
  BackEnd/main.go
Labels: sprint 2

#65 CORS has been added
  BackEnd/go.mod
  BackEnd/go.sum
  BackEnd/main.go
Labels: sprint 2

#72 Added unit test case for createcustomerapi
  BackEnd/Customer/CreateCustomer_test.go
Labels: sprint 2

#85 Wrote test cases for Navbar component and Courts component
  CourtLink/cypress/cypress.config.ts
  CourtLink/src/app/app.component.spec.ts
  CourtLink/src/app/components/courts/courts.component.spec.ts
  CourtLink/src/app/components/navbar/navbar.component.spec.ts
  CourtLink/src/app/components/sports/sports.component.spec.ts
  CourtLink/src/app/services/api.service.spec.ts
  CourtLink/src/polyfills.ts
  CourtLink/src/test.ts
Labels: enhancement, sprint 2

#90 Parsing the JSON from backend and displaying timeslots from Array data
  CourtLink/src/app/components/courts/courts.component.html
  CourtLink/src/app/components/courts/courts.component.ts
Labels: enhancement, sprint 2

#91 swagger documentation for create booking api
  BackEnd/Bookings/CreateBooking.go
  BackEnd/Customer/CreateCustomer.go
  BackEnd/docs/docs.go
  BackEnd/docs/swagger.json
  BackEnd/docs/swagger.yaml
  CourtLink.db
Labels: sprint 2

#95 Sample data added for customer
  CourtLink.db
Labels: sprint 2, testing

#106 Added the confirm dialogue box
  CourtLink/src/app/components/courts/courts.component.html
  CourtLink/src/app/components/courts/courts.component.ts
  CourtLink/src/app/services/api.service.ts
Labels: enhancement, sprint 3

#115 Implemented create sport api fully
  BackEnd/Sport/CreateSport.go
Labels: enhancement, sprint 3

#116 the customer id can now be fetched based on the emailid passed and booking can happen
  BackEnd/Court/UpdateCourts.go
  CourtLink.db
Labels: enhancement, sprint 3

#121 Added List API to fetch all sports
  BackEnd/Sport/ListSports.go
  BackEnd/main.go
Labels: enhancement, sprint 3

#126 Added the logic to update the booking status for cancellation
  BackEnd/Court/UpdateCourts.go
  CourtLink.db
Labels: enhancement, sprint 3

#131 Created a new component and routed it to the My Bookings Button
  CourtLink/src/app/app.routes.ts
  CourtLink/src/app/components/my-bookings/my-bookings.component.css
  CourtLink/src/app/components/my-bookings/my-bookings.component.html
  CourtLink/src/app/components/my-bookings/my-bookings.component.spec.ts
  CourtLink/src/app/components/my-bookings/my-bookings.component.ts
  CourtLink/src/app/components/navbar/navbar.component.html
  CourtLink/src/app/components/navbar/navbar.component.ts
  CourtLink/src/app/routes.ts
Labels: enhancement, sprint 3

#134 Implemented ListAPI that returns the list of courts and associated sport
  BackEnd/Court/ListCourts.go
  BackEnd/main.go
Labels: enhancement, sprint 3

#136 Created create court api which upodates new court and timeslots table
  BackEnd/Court/CreateCourt.go
  BackEnd/main.go
  CourtLink.db
Labels: enhancement, sprint 3

#140 Added delete api for court
  BackEnd/Court/DeleteCourt.go
  BackEnd/main.go
  CourtLink.db
Labels: enhancement, sprint 3

#145 Made changes to the my-bookings component, booking display comeplete
  CourtLink.db
  CourtLink/src/app/components/courts/courts.component.html
  CourtLink/src/app/components/my-bookings/my-bookings.component.html
  CourtLink/src/app/components/my-bookings/my-bookings.component.ts
  CourtLink/src/app/components/navbar/navbar.component.html
  CourtLink/src/app/components/navbar/navbar.component.ts
  CourtLink/src/app/components/sports/sports.component.html
Labels: enhancement, sprint 3

#158 Unit test case for create court api
  BackEnd/Court/CreateCourt_test.go
Labels: testing, sprint 3

#160 Test case for create sport api
  BackEnd/Sport/CreateSport.go
  BackEnd/Sport/CreateSport_test.go
Labels: testing, sprint 3

#162 Added list courts api test case
  BackEnd/Court/ListCourts_test.go
Labels: testing, sprint 3

#164 added test case for list sports
  BackEnd/Sport/ListSports_test.go
Labels: testing, sprint 3

#166 Added test case for delete court api
  BackEnd/Court/DeleteCourt_test.go
Labels: testing, sprint 3

#170 Updated swagger docs for the new apis added
  BackEnd/.DS_Store
  BackEnd/Bookings/listBookings.go
  BackEnd/Court/CreateCourt.go
  BackEnd/Court/DeleteCourt.go
  BackEnd/Court/DeleteCourt_test.go
  BackEnd/Court/ListCourts.go
  BackEnd/Sport/CreateSport.go
  BackEnd/Sport/ListSports.go
  BackEnd/docs/docs.go
  BackEnd/docs/swagger.json
  BackEnd/docs/swagger.yaml
Labels: testing, sprint 3

#176 Performed Unit Testingon Navbar component Sprint 3
  CourtLink/package-lock.json
  CourtLink/package.json
  CourtLink/src/app/components/navbar/navbar.component.spec.ts
  CourtLink/tsconfig.spec.json
Labels: testing, sprint 3

#178 Performed Unit Testing on Courts Component
  CourtLink/src/app/components/courts/courts.component.spec.ts
  CourtLink/src/app/components/courts/courts.component.ts
Labels: testing, sprint 3

#180 Performed Unit Tests on My-Bookings component
  CourtLink/src/app/components/my-bookings/my-bookings.component.spec.ts
Labels: testing, sprint 3
